controller_frequency: 10.0

TrajectoryPlannerROS:

  holonomic_robot: false
  
  min_vel_x: 0.1
  max_vel_x: 0.4
  min_in_place_vel_theta: 0.4
  max_vel_theta: 1.0
  escape_vel: -0.5

  meter_scoring: true
  pdist_scale: 2.0
  gdist_scale: 0.5
  occdist_scale: 0.01
  heading_lookahead: 1.0

  prune_plan: true
